### ISSUE TITLE
InternalException: E_ASSERTION_FAILURE Column type conversion from TD<type=INT64, dim=0> to TD<type=FLOAT64, dim=0>

### ISSUE THREAD

**Issue by maohui** [man-group/ArcticDB#1169]
### Describe the bug

When I read data from library, it reoorts this error message:
The DB architecture is like this: universe ['T120', 'T120_cluster3']
Then I query DB: T120_cluster3, `ac['universe'].read('T120_cluster3').data`
It shows:
```
[2023-12-17 12:56:34.634] [arcticdb] [error] E_ASSERTION_FAILURE Column type conversion from TD<type=INT64, dim=0> to TD<type=FLOAT64, dim=0> not implemented in column 3:sector -> 3:sector
[2023-12-17 12:56:34.634] [arcticdb] [error] E_ASSERTION_FAILURE Column type conversion from TD<type=INT64, dim=0> to TD<type=FLOAT64, dim=0> not implemented in column 3:sector -> 3:sector
[2023-12-17 12:56:34.634] [arcticdb] [error] E_ASSERTION_FAILURE Column type conversion from TD<type=INT64, dim=0> to TD<type=FLOAT64, dim=0> not implemented in column 3:sector -> 3:sector
```

### Steps/Code to Reproduce

```
ac['universe'].read('T120_cluster3').data
```

### Expected Results

return result dataframe

### OS, Python Version and ArcticDB Version

Python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
OS: Linux-5.4.0-162-generic-x86_64-with-glibc2.31

ArcticDB: 4.0.0

### Backend storage used

LMDB

**Comment by joe-iddon** [comment]
Thank you for taking the time to submit a bug report. It is much easier to improve ArcticDB when we hear from our users.

To help fix this problem would you please provide a minimal working example for you how came across this error. This needs to include the data that your are writing to the symbols.

I would guess though that you might have intentionally or unintentionally appended float data to a column which was an integer data type. If you would like to be able to do this, you'll need a library with dynamic schema enabled. If you search docs.arcticdb.io you'll find more information on this, but please see an example below.

```python
>>> # set up a normal library called `l` first
>>> l.read('s')
VersionedItem(symbol='s', library='l', data=<class 'pandas.core.frame.DataFrame'>, version=0, metadata=None, host='MEM()')
>>> l.read('s').data
   a
0  1
1  2
2  3
>>> l.append('s', pd.DataFrame({'a': [4,5,6]}))
VersionedItem(symbol='s', library='l', data=n/a, version=1, metadata=None, host='MEM()')
>>> l.read('s').data
   a
0  1
1  2
2  3
3  4
4  5
5  6
>>> l.append('s', pd.DataFrame({'a': [7.8]}))
VersionedItem(symbol='s', library='l', data=n/a, version=2, metadata=None, host='MEM()')
>>> # reading the symbol now will give an error as dynamic schema is disabled by default
>>> l.read('s').data
[2023-12-18 11:58:14.994] [arcticdb] [error] E_ASSERTION_FAILURE Column type conversion from TD<type=INT64, dim=0> to TD<type=FLOAT64, dim=0> not implemented in column 0:a -> 0:a
[2023-12-18 11:58:14.994] [arcticdb] [error] E_ASSERTION_FAILURE Column type conversion from TD<type=INT64, dim=0> to TD<type=FLOAT64, dim=0> not implemented in column 0:a -> 0:a
Traceback (most recent call last):
    [removed traceback]
    return ReadResult(*self.version_store.read_dataframe_version(symbol, version_query, read_query, read_options))
arcticdb_ext.exceptions.InternalException: E_ASSERTION_FAILURE Column type conversion from TD<type=INT64, dim=0> to TD<type=FLOAT64, dim=0> not implemented in column 0:a -> 0:a
>>> # if you want to use dynamic schema, this is how you enable it
>>> a.create_library('l2', library_options=arcticdb.LibraryOptions(dynamic_schema=True))
Library(Arctic(config=MEM()), path=l2, storage=in_memory_storage)
>>> a['l2']
Library(Arctic(config=MEM()), path=l2, storage=in_memory_storage)
>>> l2 = a.create_library('l2', library_options=arcticdb.LibraryOptions(dynamic_schema=True))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/is/jiddon/pyenvs/tst/lib/python3.8/site-packages/arcticdb/arctic.py", line 286, in create_library
    raise ValueError(f"Library [{name}] already exists.")
ValueError: Library [l2] already exists.
>>> l2 = a['l2']
>>> l2.write('s', 
KeyboardInterrupt
>>> l2.write('s', pd.DataFrame({'a':[1,2,3]}))
VersionedItem(symbol='s', library='l2', data=n/a, version=0, metadata=None, host='MEM()')
>>> l2.append('s', pd.DataFrame({'a': [7.8]}))
[2023-12-18 11:59:33.219] [arcticdb] [info] Got incompatible types: TD<type=FLOAT64, dim=0> TD<type=INT64, dim=0>
VersionedItem(symbol='s', library='l2', data=n/a, version=1, metadata=None, host='MEM()')
>>> # we can now append float data to an integer column and successfully read it back
>>> l2.read('s').data
     a
0  1.0
1  2.0
2  3.0
3  7.8
```

**Comment by joe-iddon** [comment]
Thank you for taking the time to submit a bug report. It is much easier to improve ArcticDB when we hear from our users.

To help fix this problem would you please provide a minimal working example for how you came across this error. This needs to include the data that you are writing to the symbols.

I would guess though that you might have intentionally or unintentionally appended float data to a column which was an integer data type. If you would like to be able to do this, you'll need a library with dynamic schema enabled. If you search [docs.arcticdb.io](https://docs.arcticdb.io) you'll find more information on this, but please see an example below.

```python
>>> # set up a normal library called `l` first
>>> l.read('s')
VersionedItem(symbol='s', library='l', data=<class 'pandas.core.frame.DataFrame'>, version=0, metadata=None, host='MEM()')
>>> l.read('s').data
   a
0  1
1  2
2  3
>>> l.append('s', pd.DataFrame({'a': [4,5,6]}))
VersionedItem(symbol='s', library='l', data=n/a, version=1, metadata=None, host='MEM()')
>>> l.read('s').data
   a
0  1
1  2
2  3
3  4
4  5
5  6
>>> l.append('s', pd.DataFrame({'a': [7.8]}))
VersionedItem(symbol='s', library='l', data=n/a, version=2, metadata=None, host='MEM()')
>>> # reading the symbol now will give an error as dynamic schema is disabled by default
>>> l.read('s').data
[2023-12-18 11:58:14.994] [arcticdb] [error] E_ASSERTION_FAILURE Column type conversion from TD<type=INT64, dim=0> to TD<type=FLOAT64, dim=0> not implemented in column 0:a -> 0:a
[2023-12-18 11:58:14.994] [arcticdb] [error] E_ASSERTION_FAILURE Column type conversion from TD<type=INT64, dim=0> to TD<type=FLOAT64, dim=0> not implemented in column 0:a -> 0:a
Traceback (most recent call last):
    [removed traceback]
    return ReadResult(*self.version_store.read_dataframe_version(symbol, version_query, read_query, read_options))
arcticdb_ext.exceptions.InternalException: E_ASSERTION_FAILURE Column type conversion from TD<type=INT64, dim=0> to TD<type=FLOAT64, dim=0> not implemented in column 0:a -> 0:a
>>> # if you want to use dynamic schema, this is how you enable it
>>> a.create_library('l2', library_options=arcticdb.LibraryOptions(dynamic_schema=True))
Library(Arctic(config=MEM()), path=l2, storage=in_memory_storage)
>>> a['l2']
Library(Arctic(config=MEM()), path=l2, storage=in_memory_storage)
>>> l2 = a.create_library('l2', library_options=arcticdb.LibraryOptions(dynamic_schema=True))
Traceback (most recent call last):
  [removed traceback]
    raise ValueError(f"Library [{name}] already exists.")
ValueError: Library [l2] already exists.
>>> l2 = a['l2']
>>> l2.write('s', 
KeyboardInterrupt
>>> l2.write('s', pd.DataFrame({'a':[1,2,3]}))
VersionedItem(symbol='s', library='l2', data=n/a, version=0, metadata=None, host='MEM()')
>>> l2.append('s', pd.DataFrame({'a': [7.8]}))
[2023-12-18 11:59:33.219] [arcticdb] [info] Got incompatible types: TD<type=FLOAT64, dim=0> TD<type=INT64, dim=0>
VersionedItem(symbol='s', library='l2', data=n/a, version=1, metadata=None, host='MEM()')
>>> # we can now append float data to an integer column and successfully read it back
>>> l2.read('s').data
     a
0  1.0
1  2.0
2  3.0
3  7.8
```

**Comment by maohui** [comment]
thanks for your demostration. I know the reason, I did not add library_options=arcticdb.LibraryOptions(dynamic_schema=True), when I create lubrary.
