### ISSUE TITLE
Read invalid serialized key

### ISSUE THREAD

**Issue by philsv** [man-group/ArcticDB#1177]
### Describe the bug

I tried to backup my entire bucket yesterday with cyberduck. I stoped midway as it took way to long. Today I encounter this traceback error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\user\anaconda3\envs\py11\Lib\site-packages\arcticdb\arctic.py", line 342, in list_libraries
    return self._library_manager.list_libraries()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
arcticdb_ext.exceptions.InternalException: E_ASSERTION_FAILURE Read invalid serialized key

I couldn't find any issue regard this InternalException. 

Connecting to the s3 bucket is working but it errors out at ac.list_libraries() - trying to list my libaries.

Any hint what might went wrong here?

### Steps/Code to Reproduce

```python
ac = Arctic(s3_bucket_uri)
ac.list_libraries()
```

### Expected Results

It should print out the list of my libraries

### OS, Python Version and ArcticDB Version

Python: 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:12:32) [MSC v.1929 64 bit (AMD64)] | OS: Windows-10-10.0.22621-SP0 | ArcticDB: 4.2.1

### Backend storage used

AWS S3

**Comment by philsv** [comment]
Hi @alexowens90 thank you for your response.

On one of my libraries I frequently get this warning now:

[2023-12-29 04:44:30.145] [arcticdb] [error] E_ASSERTION_FAILURE Cannot write string symbol name, existing symbols are numeric

[2023-12-29 04:44:30.462] [arcticdb] [warning] Ignoring error while trying to compact the symbol list: E_ASSERTION_FAILURE Cannot write string symbol name, existing symbols are numeric

Could this be related? That might be the issue.

I don't think its because of the library per se as they are all written like -> alternative_data or equity.  
No numbers or special characters
