### ISSUE TITLE
Normalizers don't work on non-string names for pandas.Series

### ISSUE THREAD

**Issue by vasil-pashov** [man-group/ArcticDB#1213]
### Describe the bug

When writing a `pandas.Series` with non-string name it is not normalized while, writing a DataFrame with one column and the same non-string name works. For example this works as expected:

### Steps/Code to Reproduce

```python
from arcticdb import Arctic
import pandas as pd
import numpy as np
ac = Arctic("lmdb://test")
lib = ac.get_library("test", create_if_missing=True)
data = pd.Series([1,2,3], name=pd.to_datetime("today"))
lib.write("non-string-name", data)
```

Throws:
```
[2024-01-08 17:53:43.271] [arcticdb] [error] Could not normalize item of type: <class 'pandas.core.series.Series'> with any normalizer.You can set pickle_on_failure param to force pickling of this object instead.(Note: Pickling has worse performance and stricter memory limitations)
[2024-01-08 17:53:43.272] [arcticdb] [error] Error while normalizing symbol=non-string-name, data=0    1
1    2
2    3
Name: 2024-01-08 17:53:04.751174, dtype: int64, metadata=None, decoding to str: need a bytes-like object, Timestamp found
Traceback (most recent call last):
  File "C:\Users\vasil\Documents\ArcticDB\python\arcticdb\version_store\_store.py", line 334, in _try_normalize
    item, norm_meta = self._normalizer.normalize(
  File "C:\Users\vasil\Documents\ArcticDB\python\arcticdb\version_store\_normalization.py", line 1211, in normalize
    return self._normalize(
  File "C:\Users\vasil\Documents\ArcticDB\python\arcticdb\version_store\_normalization.py", line 1158, in _normalize
    return normalizer(
  File "C:\Users\vasil\Documents\ArcticDB\python\arcticdb\version_store\_normalization.py", line 581, in normalize
    norm.series.common.name = _column_name_to_strings(item.name)
  File "C:\Users\vasil\Documents\ArcticDB\python\arcticdb\version_store\_common.py", line 152, in _column_name_to_strings
    return _stringify(name)
  File "C:\Users\vasil\Documents\ArcticDB\python\arcticdb\version_store\_common.py", line 18, in _stringify
    return str(v, "utf-8")
TypeError: decoding to str: need a bytes-like object, Timestamp found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\vasil\Documents\ArcticDB\python\arcticdb\version_store\library.py", line 425, in write
    return self._nvs.write(
  File "C:\Users\vasil\Documents\ArcticDB\python\arcticdb\version_store\_store.py", line 562, in write
    udm, item, norm_meta = self._try_normalize(
  File "C:\Users\vasil\Documents\ArcticDB\python\arcticdb\version_store\_store.py", line 347, in _try_normalize
    raise ArcticNativeException(str(ex))
arcticdb_ext.exceptions.ArcticException: decoding to str: need a bytes-like object, Timestamp found
```

```python
from arcticdb import Arctic
import pandas as pd
import numpy as np
ac = Arctic("lmdb://test")
lib = ac.get_library("test", create_if_missing=True)
data = pd.DataFrame([1,2,3], columns=[pd.to_datetime("today")])
lib.write("non-string-name", data)
```

### Expected Results

Non-string name of `pandas.Series` should be normalized the same way as non-string name of `pandas.DataFrame` column

### OS, Python Version and ArcticDB Version

all

**Comment by alexowens90** [comment]
Fixed by #1170 ,only strings and ints allowed as both column and index names now
