### ISSUE TITLE
Multi-Column dataframe can't be written

### ISSUE THREAD

**Issue by claudiocmp** [man-group/ArcticDB#1220]
### Describe the bug

DataFrame with multi-index column cannot be added.

According to this issue, feature should be implemented: https://github.com/man-group/ArcticDB/issues/285
However, I see here an example where multi-index columns are flatten before storage: https://github.com/man-group/ArcticDB/issues/454

### Steps/Code to Reproduce

```
from arcticdb import Arctic
import pandas as pd

arc = Arctic('lmdb:///home/claudio.campanile@chesterfield.local/dev/tests/data')

df = pd.DataFrame(
    [[1,2,3,4],[3,4,5,6],[5,6,7,8],[8,9,10,11]],
    columns=pd.MultiIndex.from_product([['a', 'b'],['a', 'b']]),
    index=pd.MultiIndex.from_product([[1,2],[1,2]])
)

arc.create_library('test')
lib = arc.get_library('test')
lib.write('TestSymbol', df, {'foo': 'goo'})
```

output:
```
Exception has occurred: ArcticDbNotYetImplemented
MultiIndex column are not supported yet
  File "/home/claudio.campanile@chesterfield.local/dev/tests/arctic_db_test.py", line 14, in <module>
    lib.write('TestSymbol', df, {'foo': 'goo'})
arcticdb.exceptions.ArcticDbNotYetImplemented: MultiIndex column are not supported yet
```

### Expected Results

```
... # as above
>>> read_back = lib.read('TestSymbol')
>>> read_back
     a  a   b   b
     a  b   a   b
1 1  1  2   3   4
  2  3  4   5   6
2 1  5  6   7   8
  2  8  9  10  11
```

If flatten multi columns is a requirement before saving, error message should specify it.

### OS, Python Version and ArcticDB Version

```
Python: 3.7.15 (default, Oct 12 2022, 19:14:01) 
[GCC 11.2.0]
OS: Linux-6.2.0-1017-azure-x86_64-with-Ubuntu-22.04-jammy
ArcticDB: 4.2.1
```
```
$ pip list | grep pandas
pandas             1.3.5
```

### Backend storage used

LMDB

### Additional Context

I haven't tested it against S3 or Azure.

**Comment by claudiocmp** [comment]
Same applies to S3:
```
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/home/claudio.campanile@chesterfield.local/dev/tests/venv/lib/python3.7/site-packages/arcticdb/version_store/library.py", line 432, in write
    validate_index=validate_index,
  File "/home/claudio.campanile@chesterfield.local/dev/tests/venv/lib/python3.7/site-packages/arcticdb/version_store/_store.py", line 563, in write
    symbol, data, metadata, pickle_on_failure, dynamic_strings, coerce_columns
  File "/home/claudio.campanile@chesterfield.local/dev/tests/venv/lib/python3.7/site-packages/arcticdb/version_store/_store.py", line 340, in _try_normalize
    **kwargs,
  File "/home/claudio.campanile@chesterfield.local/dev/tests/venv/lib/python3.7/site-packages/arcticdb/version_store/_normalization.py", line 1206, in normalize
    **kwargs,
  File "/home/claudio.campanile@chesterfield.local/dev/tests/venv/lib/python3.7/site-packages/arcticdb/version_store/_normalization.py", line 1153, in _normalize
    **kwargs,
  File "/home/claudio.campanile@chesterfield.local/dev/tests/venv/lib/python3.7/site-packages/arcticdb/version_store/_normalization.py", line 828, in normalize
    raise ArcticDbNotYetImplemented("MultiIndex column are not supported yet")
arcticdb.exceptions.ArcticDbNotYetImplemented: MultiIndex column are not supported yet
```
