### ISSUE TITLE
arcticdb 4.4.0 undefined symbol _ZN6snappy8CompressEPNS_6SourceEPNS_4SinkE

### ISSUE THREAD

**Issue by jamesmunro** [man-group/ArcticDB#1479]
### Describe the bug

A clean `micromamba` environment and `arcticdb==4.4.0` gives this import error
```
>>> import arcticdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/james/micromamba/envs/test/lib/python3.11/site-packages/arcticdb/__init__.py", line 1, in <module>
    import arcticdb_ext as _ext
ImportError: /home/james/micromamba/envs/test/lib/python3.11/site-packages/../../libfolly.so.0.58.0-dev: undefined symbol: _ZN6snappy8CompressEPNS_6SourceEPNS_4SinkE
>>>
```

### Steps/Code to Reproduce

```
micromamba create -n test arcticdb==4.4.0
micromamba activate test
python
>>> import arcticdb
```

### Expected Results

`import arcticdb` works

### OS, Python Version and ArcticDB Version

Python: 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:53:32) [GCC 12.3.0]
OS: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

### Additional Context
```
(test) james@desktop-node202:~$ micromamba list
List of packages in environment: "/home/james/micromamba/envs/test"

  Name                      Version        Build                Channel
─────────────────────────────────────────────────────────────────────────────
  _libgcc_mutex             0.1            conda_forge          conda-forge
  _openmp_mutex             4.5            2_gnu                conda-forge
  arcticdb                  4.4.0          py311hdb8dc4b_0      conda-forge
  attrs                     23.2.0         pyh71513ae_0         conda-forge
  aws-c-auth                0.7.16         haed3651_8           conda-forge
  aws-c-cal                 0.6.10         ha9bf9b1_2           conda-forge
  aws-c-common              0.9.14         hd590300_0           conda-forge
  aws-c-compression         0.2.18         h4466546_2           conda-forge
  aws-c-event-stream        0.4.2          he635cd5_6           conda-forge
  aws-c-http                0.8.1          hbfc29b2_7           conda-forge
  aws-c-io                  0.14.6         h96cd748_2           conda-forge
  aws-c-mqtt                0.10.3         hffff1cc_2           conda-forge
  aws-c-s3                  0.5.5          h4893938_0           conda-forge
  aws-c-sdkutils            0.1.15         h4466546_2           conda-forge
  aws-checksums             0.1.18         h4466546_2           conda-forge
  aws-crt-cpp               0.26.4         h58a74b7_3           conda-forge
  aws-sdk-cpp               1.11.267       hb1af6a8_4           conda-forge
  azure-core-cpp            1.11.1         h91d86a7_1           conda-forge
  azure-identity-cpp        1.6.0          hf1915f5_1           conda-forge
  azure-storage-blobs-cpp   12.10.0        h00ab1b0_1           conda-forge
  azure-storage-common-cpp  12.5.0         h94269e2_4           conda-forge
  bzip2                     1.0.8          hd590300_5           conda-forge
  c-ares                    1.28.1         hd590300_0           conda-forge
  ca-certificates           2024.2.2       hbcca054_0           conda-forge
  cyrus-sasl                2.1.27         h54b06d7_7           conda-forge
  decorator                 5.1.1          pyhd8ed1ab_0         conda-forge
  double-conversion         3.3.0          h59595ed_0           conda-forge
  fmt                       10.2.1         h00ab1b0_0           conda-forge
  folly                     2024.02.19.00  h72ab1f5_2_jemalloc  conda-forge
  gflags                    2.2.2          he1b5a44_1004        conda-forge
  glog                      0.7.0          hed5481d_0           conda-forge
  gtest                     1.14.0         h00ab1b0_1           conda-forge
  icu                       73.2           h59595ed_0           conda-forge
  jemalloc                  5.3.0          hcb278e6_0           conda-forge
  keyutils                  1.6.1          h166bdaf_0           conda-forge
  krb5                      1.21.2         h659d440_0           conda-forge
  ld_impl_linux-64          2.40           h41732ed_0           conda-forge
  libabseil                 20240116.1     cxx17_h59595ed_2     conda-forge
  libaio                    0.3.113        h166bdaf_0           conda-forge
  libblas                   3.9.0          21_linux64_openblas  conda-forge
  libboost                  1.82.0         h6fcfa73_6           conda-forge
  libboost-headers          1.84.0         ha770c72_2           conda-forge
  libbson                   1.23.2         hcb278e6_0           conda-forge
  libcblas                  3.9.0          21_linux64_openblas  conda-forge
  libcurl                   8.7.1          hca28451_0           conda-forge
  libedit                   3.1.20191231   he28a2e2_2           conda-forge
  libev                     4.33           hd590300_2           conda-forge
  libevent                  2.1.12         hf998b51_1           conda-forge
  libexpat                  2.6.2          h59595ed_0           conda-forge
  libffi                    3.4.2          h7f98852_5           conda-forge
  libgcc-ng                 13.2.0         h807b86a_5           conda-forge
  libgfortran-ng            13.2.0         h69a702a_5           conda-forge
  libgfortran5              13.2.0         ha4646dd_5           conda-forge
  libgomp                   13.2.0         h807b86a_5           conda-forge
  libiconv                  1.17           hd590300_2           conda-forge
  libjemalloc               5.3.0          hcb278e6_0           conda-forge
  liblapack                 3.9.0          21_linux64_openblas  conda-forge
  libmongoc                 1.23.2         haec5f90_0           conda-forge
  libmongocxx               3.7.2          h59595ed_1           conda-forge
  libnghttp2                1.58.0         h47da74e_1           conda-forge
  libnsl                    2.0.1          hd590300_0           conda-forge
  libntlm                   1.4            h7f98852_1002        conda-forge
  libopenblas               0.3.26         pthreads_h413a1c8_0  conda-forge
  libprotobuf               4.25.3         h08a7969_0           conda-forge
  libsodium                 1.0.18         h36c2ea0_1           conda-forge
  libsqlite                 3.45.2         h2797004_0           conda-forge
  libssh2                   1.11.0         h0841786_0           conda-forge
  libstdcxx-ng              13.2.0         h7e041cc_5           conda-forge
  libuuid                   2.38.1         h0b41bf4_0           conda-forge
  libxcrypt                 4.4.36         hd590300_1           conda-forge
  libxml2                   2.12.6         h232c23b_1           conda-forge
  libzlib                   1.2.13         hd590300_5           conda-forge
  lmdb                      0.9.22         hd590300_1001        conda-forge
  lz4-c                     1.9.4          hcb278e6_0           conda-forge
  msgpack-c                 6.0.0          hfc55251_1           conda-forge
  msgpack-python            1.0.7          py311h9547e67_0      conda-forge
  ncurses                   6.4.20240210   h59595ed_0           conda-forge
  numpy                     1.26.4         py311h64a7726_0      conda-forge
  openssl                   3.2.1          hd590300_1           conda-forge
  packaging                 24.0           pyhd8ed1ab_0         conda-forge
  pandas                    2.2.1          py311h320fe9a_0      conda-forge
  pcre                      8.45           h9c3ff4c_0           conda-forge
  pip                       24.0           pyhd8ed1ab_0         conda-forge
  prometheus-cpp            1.2.4          h90a924e_0           conda-forge
  protobuf                  4.25.3         py311h7b78aeb_0      conda-forge
  psutil                    5.9.8          py311h459d7ec_0      conda-forge
  python                    3.11.8         hab00c5b_0_cpython   conda-forge
  python-dateutil           2.9.0          pyhd8ed1ab_0         conda-forge
  python-tzdata             2024.1         pyhd8ed1ab_0         conda-forge
  python_abi                3.11           4_cp311              conda-forge
  pytz                      2024.1         pyhd8ed1ab_0         conda-forge
  pyyaml                    6.0.1          py311h459d7ec_1      conda-forge
  readline                  8.2            h8228510_1           conda-forge
  s2n                       1.4.8          h06160fa_0           conda-forge
  setuptools                69.2.0         pyhd8ed1ab_0         conda-forge
  six                       1.16.0         pyh6c4a22f_0         conda-forge
  snappy                    1.2.0          hdb0a2a9_0           conda-forge
  spdlog                    1.12.0         hd2e6256_2           conda-forge
  tk                        8.6.13         noxft_h4845f30_101   conda-forge
  tzdata                    2024a          h0c530f3_0           conda-forge
  wheel                     0.43.0         pyhd8ed1ab_1         conda-forge
  xxhash                    0.8.2          hd590300_0           conda-forge
  xz                        5.2.6          h166bdaf_0           conda-forge
  yaml                      0.2.5          h7f98852_2           conda-forge
  zlib                      1.2.13         hd590300_5           conda-forge
  zstd                      1.5.5          hfc55251_0           conda-forge
(test) james@desktop-node202:~$
```

**Comment by jamesmunro** [comment]
Also happens with ``python==3.9.12```

**Comment by jamesmunro** [comment]
Looks to be related to release `1.2.0` of snappy on conda-forge.
https://anaconda.org/conda-forge/snappy/files
<img width="734" alt="image" src="https://github.com/man-group/ArcticDB/assets/283605/10fc5fc1-9045-403f-ad9a-1b9623da795b">

**Comment by jjerphan** [comment]
Due to https://github.com/conda-forge/snappy-feedstock/issues/35.

**Comment by jamesmunro** [comment]
Resolved for now by https://github.com/conda-forge/admin-requests/pull/973
