### ISSUE TITLE
E_ASSERTION_FAILURE Index mismatch, cannot update a timeseries with a non-timeseries-indexed frame

### ISSUE THREAD

**Issue by philsv** [man-group/ArcticDB#1627]
### Describe the bug

Simular to https://github.com/man-group/ArcticDB/issues/1626

I can run this code locally with no issues, but when running in bitbucket pipelines I get the following stdout error:

```
+ python3.11 -m src.modules.mc_clellan

2024-06-18 16:40:30 - mc_clellan_ad_oscillator_full_dataset update_df (update) info:

<class 'pandas.core.frame.DataFrame'>

DatetimeIndex: 493 entries, 2022-07-01 to 2024-06-17

Data columns (total 23 columns):

 #   Column                                                 Non-Null Count  Dtype  

---  ------                                                 --------------  -----  

 0   NYSE Advance                                           493 non-null    float64

 1   NYSE Decline                                           493 non-null    float64

 2   NYSE Up Volume (x 1000)                                493 non-null    float64

 3   NYSE Down Volume (x 1000)                              493 non-null    float64

 4   DJIA Close                                             493 non-null    float64

 5   NYSE Advance-Decline                                   493 non-null    float64

 6   10% Trend Advance-Decline                              493 non-null    float64

 7   5% Trend Advance-Decline                               493 non-null    float64

 8   McClellan Advance-Decline Oscillator                   493 non-null    float64

 9   McClellan Advance-Decline Oscillator Breath            493 non-null    float64

 10  Advance-Decline for Oscillator Unchanged Tomorrow      493 non-null    float64

 11  Advance-Decline for Oscillator To 0 Tomorrow           493 non-null    float64

 12  NYSE Up Volume / Down Volume (x 1000)                  493 non-null    float64

 13  10% Trend Up Volume / Down Volume                      493 non-null    float64

 14  5% Trend Up Volume / Down Volume                       493 non-null    float64

 15  McClellan Up Volume Oscillator                         493 non-null    float64

 16  McClellan Down Volume Oscillator Breath                493 non-null    float64

 17  Up Volume / Down Volume Oscillator Unchanged Tomorrow  493 non-null    float64

 18  Up Volume / Down Volume Oscillator To 0 Tomorrow       493 non-null    float64

 19  10% Trend DJIA Close                                   493 non-null    float64

 20  5% Trend DJIA Close                                    493 non-null    float64

 21  DJIA Price Oscillator                                  493 non-null    float64

 22  DJIA Price For Unchanged Oscillator                    493 non-null    float64

dtypes: float64(23)

memory usage: 92.4 KB

[2024-06-18 16:40:30.623] [arcticdb] [error] E_ASSERTION_FAILURE Index mismatch, cannot update a timeseries with a non-timeseries-indexed frame

Traceback (most recent call last):

  File "/opt/atlassian/pipelines/agent/build/src/arctic/db.py", line 238, in write_to_db

    df = library.update(symbol, update_df, upsert=True).data

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/arcticdb/version_store/library.py", line 862, in update

    return self._nvs.update(

           ^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/arcticdb/version_store/_store.py", line 807, in update

    vit = self.version_store.update(

          ^^^^^^^^^^^^^^^^^^^^^^^^^^

arcticdb_ext.exceptions.InternalException: E_ASSERTION_FAILURE Index mismatch, cannot update a timeseries with a non-timeseries-indexed frame
```

Another try, can't update the dataframe even though it is timeseries-indexed.

```
+ python3.10 -m src.modules.mc_clellan

2024-06-19 01:41:45 - mc_clellan_ad_oscillator_full_dataset old df (before update) info:

<class 'pandas.core.frame.DataFrame'>

DatetimeIndex: 491 entries, 2022-07-01 to 2024-06-13

Data columns (total 23 columns):

 #   Column                                                 Non-Null Count  Dtype  

---  ------                                                 --------------  -----  

 0   NYSE Advance                                           491 non-null    float64

 1   NYSE Decline                                           491 non-null    float64

 2   NYSE Up Volume (x 1000)                                491 non-null    float64

 3   NYSE Down Volume (x 1000)                              491 non-null    float64

 4   DJIA Close                                             491 non-null    float64

 5   NYSE Advance-Decline                                   491 non-null    float64

 6   10% Trend Advance-Decline                              491 non-null    float64

 7   5% Trend Advance-Decline                               491 non-null    float64

 8   McClellan Advance-Decline Oscillator                   491 non-null    float64

 9   McClellan Advance-Decline Oscillator Breath            491 non-null    float64

 10  Advance-Decline for Oscillator Unchanged Tomorrow      491 non-null    float64

 11  Advance-Decline for Oscillator To 0 Tomorrow           491 non-null    float64

 12  NYSE Up Volume / Down Volume (x 1000)                  491 non-null    float64

 13  10% Trend Up Volume / Down Volume                      491 non-null    float64

 14  5% Trend Up Volume / Down Volume                       491 non-null    float64

 15  McClellan Up Volume Oscillator                         491 non-null    float64

 16  McClellan Down Volume Oscillator Breath                491 non-null    float64

 17  Up Volume / Down Volume Oscillator Unchanged Tomorrow  491 non-null    float64

 18  Up Volume / Down Volume Oscillator To 0 Tomorrow       491 non-null    float64

 19  10% Trend DJIA Close                                   491 non-null    float64

 20  5% Trend DJIA Close                                    491 non-null    float64

 21  DJIA Price Oscillator                                  491 non-null    float64

 22  DJIA Price For Unchanged Oscillator                    491 non-null    float64

dtypes: float64(23)

memory usage: 92.1 KB

2024-06-19 01:41:45 - mc_clellan_ad_oscillator_full_dataset df (before update) info:

<class 'pandas.core.frame.DataFrame'>

DatetimeIndex: 494 entries, 2022-07-01 to 2024-06-18

Data columns (total 23 columns):

 #   Column                                                 Non-Null Count  Dtype  

---  ------                                                 --------------  -----  

 0   NYSE Advance                                           494 non-null    float64

 1   NYSE Decline                                           494 non-null    float64

 2   NYSE Up Volume (x 1000)                                494 non-null    float64

 3   NYSE Down Volume (x 1000)                              494 non-null    float64

 4   DJIA Close                                             494 non-null    float64

 5   NYSE Advance-Decline                                   494 non-null    float64

 6   10% Trend Advance-Decline                              494 non-null    float64

 7   5% Trend Advance-Decline                               494 non-null    float64

 8   McClellan Advance-Decline Oscillator                   494 non-null    float64

 9   McClellan Advance-Decline Oscillator Breath            494 non-null    float64

 10  Advance-Decline for Oscillator Unchanged Tomorrow      494 non-null    float64

 11  Advance-Decline for Oscillator To 0 Tomorrow           494 non-null    float64

 12  NYSE Up Volume / Down Volume (x 1000)                  494 non-null    float64

 13  10% Trend Up Volume / Down Volume                      494 non-null    float64

 14  5% Trend Up Volume / Down Volume                       494 non-null    float64

 15  McClellan Up Volume Oscillator                         494 non-null    float64

 16  McClellan Down Volume Oscillator Breath                494 non-null    float64

 17  Up Volume / Down Volume Oscillator Unchanged Tomorrow  494 non-null    float64

 18  Up Volume / Down Volume Oscillator To 0 Tomorrow       494 non-null    float64

 19  10% Trend DJIA Close                                   494 non-null    float64

 20  5% Trend DJIA Close                                    494 non-null    float64

 21  DJIA Price Oscillator                                  494 non-null    float64

 22  DJIA Price For Unchanged Oscillator                    494 non-null    float64

dtypes: float64(23)

memory usage: 92.6 KB

2024-06-19 01:41:45 - mc_clellan_ad_oscillator_full_dataset update_df (update) info:

<class 'pandas.core.frame.DataFrame'>

DatetimeIndex: 494 entries, 2022-07-01 to 2024-06-18

Data columns (total 23 columns):

 #   Column                                                 Non-Null Count  Dtype  

---  ------                                                 --------------  -----  

 0   NYSE Advance                                           494 non-null    float64

 1   NYSE Decline                                           494 non-null    float64

 2   NYSE Up Volume (x 1000)                                494 non-null    float64

 3   NYSE Down Volume (x 1000)                              494 non-null    float64

 4   DJIA Close                                             494 non-null    float64

 5   NYSE Advance-Decline                                   494 non-null    float64

 6   10% Trend Advance-Decline                              494 non-null    float64

 7   5% Trend Advance-Decline                               494 non-null    float64

 8   McClellan Advance-Decline Oscillator                   494 non-null    float64

 9   McClellan Advance-Decline Oscillator Breath            494 non-null    float64

 10  Advance-Decline for Oscillator Unchanged Tomorrow      494 non-null    float64

 11  Advance-Decline for Oscillator To 0 Tomorrow           494 non-null    float64

 12  NYSE Up Volume / Down Volume (x 1000)                  494 non-null    float64

 13  10% Trend Up Volume / Down Volume                      494 non-null    float64

 14  5% Trend Up Volume / Down Volume                       494 non-null    float64

 15  McClellan Up Volume Oscillator                         494 non-null    float64

 16  McClellan Down Volume Oscillator Breath                494 non-null    float64

 17  Up Volume / Down Volume Oscillator Unchanged Tomorrow  494 non-null    float64

 18  Up Volume / Down Volume Oscillator To 0 Tomorrow       494 non-null    float64

 19  10% Trend DJIA Close                                   494 non-null    float64

 20  5% Trend DJIA Close                                    494 non-null    float64

 21  DJIA Price Oscillator                                  494 non-null    float64

 22  DJIA Price For Unchanged Oscillator                    494 non-null    float64

dtypes: float64(23)

memory usage: 92.6 KB

20240619 01:41:45.647391 941 E arcticdb.root | E_ASSERTION_FAILURE Index mismatch, cannot update a timeseries with a non-timeseries-indexed frame

2024-06-19 01:41:45 - Error: E_ASSERTION_FAILURE Index mismatch, cannot update a timeseries with a non-timeseries-indexed frame

Traceback (most recent call last):

  File "/opt/atlassian/pipelines/agent/build/src/arctic/db.py", line 245, in write_to_db

    updated_df = library.update(symbol, update_df, upsert=True)

  File "/usr/local/lib/python3.10/dist-packages/arcticdb/version_store/library.py", line 862, in update

    return self._nvs.update(

  File "/usr/local/lib/python3.10/dist-packages/arcticdb/version_store/_store.py", line 807, in update

    vit = self.version_store.update(

arcticdb_ext.exceptions.InternalException: E_ASSERTION_FAILURE Index mismatch, cannot update a timeseries with a non-timeseries-indexed frame
```

Since I can't make library.append() work anymore I tried to update the entry but can't make this work as well.

### Steps/Code to Reproduce

```yml
image: python:3.11.3-slim-bullseye
    mc_clellan:
      - step:
          name: "Update mcclellan"
          caches:
            - pip
          script:
              - apt-get update && apt-get install -y --no-install-recommends software-properties-common
              - export INSTALL_ON_LINUX=1
              - pip install --upgrade pip
              - pip3 install arcticdb==4.4.2 backoff pandas>=2.0.2 numpy python-dateutil python-dotenv pydantic-settings statsmodels ta xlwings requests openpyxl xlrd
              - python3.11 -m src.modules.mc_clellan
```

```python
from arcticdb import Arctic
...
ac = self.__init_db()
library = ac[lib]

...
update_df = pd.concat([df, library.read(symbol).data])
update_df = update_df[~update_df.index.duplicated(keep="last")]
df = library.update(symbol, update_df, upsert=True).data
```

### Expected Results

Update the df without a error message

### OS, Python Version and ArcticDB Version

Python 3.11.3 | Docker Image: python:3.11.3-slim-bullseye using bitbucket-pipelines.yml | OS: Debian-11 ArcticDB: 4.4.2 - 4.0.0

### Backend storage used

AWS S3

**Comment by philsv** [comment]
Switching to 4.4.3 solved this problem
