### ISSUE TITLE
Can not list symbols after change the domain of an S3 compatible storage.

### ISSUE THREAD

**Issue by freddong** [man-group/ArcticDB#235]
## Description
Can not list symbols after change the domain of an S3 compatible storage, but list_libraries() is ok.

I found the domain in arctic/_arctic_cfg/cref/ is still the old one "ceph-s3.lan:7480".

Output after domain change:
```
~$ mcli cp s3lan/arctic/_arctic_cfg/cref/*sUt*data .

~$ strings \*sUt\*data 
9type.googleapis.com/arcticc.pb2.storage_
LibraryConfig
data
1680795853320937728_>
0cxx.
J.org
A60RFKS2H77MOA4GZV1H
(Ct9KY3xUdW2WIQrD0Ea1KAc81XETVF4AWRppCAwE"
ceph-s3.lan:7480J
P37728

```

## Enviroment
ceph Quincy on proxmox with rados gateway

### read data normally

The domain in /etc/ceph/ceph.conf is `ceph-s3.lan`.

```python
import pandas as pd
import time
from datetime import datetime
import numpy as np

from arcticdb import Arctic
ac = Arctic('s3://ceph-s3.lan:7480:arctic?access=XXX&secret=YYY')

print(ac.list_libraries())

library = ac['data']
print(library.list_symbols())
```

### error throwed after change domain

Change the domain in /etc/ceph/ceph.conf to `s3.lan`.

```
python read.py                                                           
['data']      
20230417_074544.349449 105055 W arcticdb.storage 105055 | Failed to iterate key type with key 'l' NoSuchBucket: 
20230417_074544.349449 105055 W arcticdb.storage 105055 | Failed to iterate key type with key 'l' NoSuchBucket: 
20230417_074544.395526 105055 W arcticdb.storage 105055 | Failed to iterate key type with key 'r' NoSuchBucket: 
20230417_074544.395526 105055 W arcticdb.storage 105055 | Failed to iterate key type with key 'r' NoSuchBucket: 
20230417_074544.504671 105071 E arcticdb.root 105055 | E_ASSERTION_FAILURE Failed to write s3 with key 'x:SymbolListCompactionLock' NoSuchBucket: 
20230417_074544.504671 105071 E arcticdb.root 105055 | E_ASSERTION_FAILURE Failed to write s3 with key 'x:SymbolListCompactionLock' NoSuchBucket: 
20230417_074544.556769 105055 W arcticdb.storage 105055 | Failed to iterate key type with key 'l' NoSuchBucket: 
20230417_074544.556769 105055 W arcticdb.storage 105055 | Failed to iterate key type with key 'l' NoSuchBucket: 
20230417_074544.603141 105055 W arcticdb.storage 105055 | Failed to iterate key type with key 'r' NoSuchBucket: 
20230417_074544.603141 105055 W arcticdb.storage 105055 | Failed to iterate key type with key 'r' NoSuchBucket: 
20230417_074544.706768 105073 E arcticdb.root 105055 | E_ASSERTION_FAILURE Failed to write s3 with key 'x:SymbolListCompactionLock' NoSuchBucket: 
20230417_074544.706768 105073 E arcticdb.root 105055 | E_ASSERTION_FAILURE Failed to write s3 with key 'x:SymbolListCompactionLock' NoSuchBucket: 
20230417_074544.738531 105055 W arcticdb.storage 105055 | Failed to iterate key type with key 'l' NoSuchBucket: 
20230417_074544.738531 105055 W arcticdb.storage 105055 | Failed to iterate key type with key 'l' NoSuchBucket: 
20230417_074544.789593 105055 W arcticdb.storage 105055 | Failed to iterate key type with key 'r' NoSuchBucket: 
20230417_074544.789593 105055 W arcticdb.storage 105055 | Failed to iterate key type with key 'r' NoSuchBucket: 

```

**Comment by poodlewars** [comment]
Thanks for reporting. Before we can investigate, please clarify what `read.py` is doing. Can you confirm that you are re-creating the `Arctic` client with the new domain?

**Comment by freddong** [comment]
I guess the data stored contains hard-coded domain of s3 sever. 
If the files written with arcticdb are not tied with the server domain, we can simplely copy the files without modifying when we do migration between different s3 servers.

The steps to reproduce the problem:

1. Whatever the domain, I can access the server using s3 cli tool (minio client).

I can access `ceph-s3.lan`.
```
$ mcli alias ls
cephs3
  URL       : http://ceph-s3.lan:7480
  AccessKey : arctic
  SecretKey : arcticarctic
  API       : s3v4
  Path      : auto

~$ mcli ls cephs3
[2023-04-17 20:37:50 HKT]     0B arctic/
[2023-04-20 08:31:28 HKT]     0B arctic-cn/
[2023-04-17 19:17:14 HKT]     0B test/
```

After change the domain in proxmox ceph radosgw (still the same server) from `ceph-s3.lan` to `s3.lan`.

```
~$ mcli alias ls
s3lan
  URL       : http://s3.lan:7480
  AccessKey : arctic
  SecretKey : arcticarctic
  API       : s3v4
  Path      : auto

~$ mcli ls cephs3
mcli: <ERROR> Unable to list folder. The specified bucket does not exist.

~$ mcli ls s3lan
[2023-04-17 20:37:50 HKT]     0B arctic/
[2023-04-20 08:31:28 HKT]     0B arctic-cn/
[2023-04-17 19:17:14 HKT]     0B test/
```

2. Create library when domain is `ceph-s3.lan`.

write.py
```
import pandas as pd
from arcticdb import Arctic

ac = Arctic('s3://ceph-s3.lan:7480:test?access=arctic&secret=arcticarctic')

print(ac.list_libraries())

if 'data' not in ac.list_libraries():
    ac.create_library('data')
library = ac['data']
df = pd.DataFrame()
library.write("sym1", df)
```

3. Read when domain is `ceph-s3.lan`.

read.py
```
import pandas as pd
from arcticdb import Arctic

ac = Arctic('s3://ceph-s3.lan:7480:test?access=arctic&secret=arcticarctic')

print(ac.list_libraries())

library = ac['data']
df = library.read("sym1").data
print(df)
```

output
```
~$ python read.py 
['data']
Empty DataFrame
Columns: []
Index: []
```

4. Change domain, then read when domain is `s3.lan`.

read.py
```
import pandas as pd
from arcticdb import Arctic

ac = Arctic('s3://s3.lan:7480:test?access=arctic&secret=arcticarctic')

print(ac.list_libraries())

library = ac['data']
df = library.read("sym1").data
print(df)
```

output
```
~$ python read.py 
['data']
20230420_210609.921537 274020 W arcticdb.storage 274020 | Failed to iterate key type with key 'V' NoSuchBucket: 
20230420_210609.921537 274020 W arcticdb.storage 274020 | Failed to iterate key type with key 'V' NoSuchBucket: 
Traceback (most recent call last):
  File "/home/neo/read.py", line 9, in <module>
    df = library.read("sym1").data
  File "/home/neo/.virtualenvs/dlab/lib/python3.9/site-packages/arcticdb/version_store/library.py", line 805, in read
    return self._nvs.read(
  File "/home/neo/.virtualenvs/dlab/lib/python3.9/site-packages/arcticdb/version_store/_store.py", line 1329, in read
    read_result = self._read_dataframe(symbol, version_query, read_query, read_options)
  File "/home/neo/.virtualenvs/dlab/lib/python3.9/site-packages/arcticdb/version_store/_store.py", line 1394, in _read_dataframe
    return ReadResult(*self.version_store.read_dataframe_version(symbol, version_query, read_query, read_options))
arcticdb_ext.storage.NoDataFoundException: read_dataframe_version: version not found for stream 'sym1'
```

**Comment by qc00** [comment]
I would guess this is because the configuration database holds the old URL in the storage config of the library. We don't have an API (yet) for the end user to update those, unfortunately.

We should probably change the code to use relative URLs in the storage config to avoid this kind of problem.

**Comment by poodlewars** [comment]
This has been resolved, under https://github.com/man-group/ArcticDB/issues/497 .
