### ISSUE TITLE
About Windows Installation

### ISSUE THREAD

**Issue by TianQingX** [man-group/ArcticDB#295]
Dear ArcticDB group

It seems like ArcticDB's installation by pip will lead to some problems in Windows, this is my report. 

env packages, python = 3.6

![image](https://user-images.githubusercontent.com/40229906/235424521-454f8687-6f6a-4e77-86dc-43bd3d19c31b.png)

pip install arcticdb

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\cli\base_command.py", line 173, in _main
    status = self.run(options, args)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\cli\req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\commands\install.py", line 316, in run
    reqs, check_supported_wheels=not options.target_dir
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    collected.requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 341, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 140, in __bool__
    return any(self)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 128, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 29, in _iter_built
    for version, func in infos:
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 275, in iter_index_candidate_infos
    hashes=hashes,
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\index\package_finder.py", line 851, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\index\package_finder.py", line 798, in find_all_candidates
    page_candidates = list(page_candidates_it)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\index\sources.py", line 134, in page_candidates
    yield from self._candidates_from_page(self._link)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\index\package_finder.py", line 758, in process_project_url
    html_page = self._link_collector.fetch_page(project_url)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\index\collector.py", line 490, in fetch_page
    return _get_html_page(location, session=self.session)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\index\collector.py", line 400, in _get_html_page
    resp = _get_html_response(url, session=session)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\index\collector.py", line 132, in _get_html_response
    "Cache-Control": "max-age=0",
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\network\session.py", line 454, in request
    return super().request(method, url, *args, **kwargs)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\urllib3\connection.py", line 506, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\ps\anaconda3\envs\data\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\ps\anaconda3\envs\data\lib\ssl.py", line 773, in __init__
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

(data) C:\Users\ps>pip install arcticdb
ERROR: Could not find a version that satisfies the requirement arcticdb (from versions: none)
ERROR: No matching distribution found for arcticdb

(data) C:\Users\ps>pip install arcticdb==1.0.1
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\cli\base_command.py", line 173, in _main
    status = self.run(options, args)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\cli\req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\commands\install.py", line 316, in run
    reqs, check_supported_wheels=not options.target_dir
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    collected.requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 341, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 140, in __bool__
    return any(self)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 128, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 29, in _iter_built
    for version, func in infos:
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 275, in iter_index_candidate_infos
    hashes=hashes,
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\index\package_finder.py", line 851, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\index\package_finder.py", line 798, in find_all_candidates
    page_candidates = list(page_candidates_it)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\index\sources.py", line 134, in page_candidates
    yield from self._candidates_from_page(self._link)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\index\package_finder.py", line 758, in process_project_url
    html_page = self._link_collector.fetch_page(project_url)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\index\collector.py", line 490, in fetch_page
    return _get_html_page(location, session=self.session)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\index\collector.py", line 400, in _get_html_page
    resp = _get_html_response(url, session=session)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\index\collector.py", line 132, in _get_html_response
    "Cache-Control": "max-age=0",
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_internal\network\session.py", line 454, in request
    return super().request(method, url, *args, **kwargs)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\urllib3\connection.py", line 506, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\ps\anaconda3\envs\data\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\ps\anaconda3\envs\data\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\ps\anaconda3\envs\data\lib\ssl.py", line 773, in __init__
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

Also, when I use VPN, there will be other mistakes in another test env in python = 3.5

![image](https://user-images.githubusercontent.com/40229906/235425238-81fe4d58-1440-4d9f-875b-923dae80939e.png)

**Comment by nick-voisin** [comment]
They haven't yet published their Windows wheel to PyPI. You can see it in their Github Actions pipeline : https://github.com/man-group/ArcticDB/actions/runs/4830924624/jobs/8608012869 - publish is unchecked.

**Comment by qc00** [comment]
Office Windows binary is expected in the next minor release, which will hopefully be cut this week and uploaded early next week.

**Comment by qc00** [comment]
We're pleased to announce [v1.1.0](https://github.com/man-group/ArcticDB/releases/tag/v1.1.0) has been released to [Pypi](https://pypi.org/project/arcticdb/) with Windows builds.

**Comment by TianQingX** [comment]
> We're pleased to announce [v1.1.0](https://github.com/man-group/ArcticDB/releases/tag/v1.1.0) has been released to [Pypi](https://pypi.org/project/arcticdb/) with Windows builds.

Love to hear that!
