### ISSUE TITLE
Failing test suites for Python 3.6 on Linux

### ISSUE THREAD

**Issue by jjerphan** [man-group/ArcticDB#336]
Currently, all the test suites for Python 3.6 on Linux fail on the CI for some PRs. The error is not reported on the CI run (see [this one](https://github.com/man-group/ArcticDB/actions/runs/4884944351/jobs/8732304989?pr=320#step:9:26) for instance).

I have setup and build ArcticDB at 134b72a2fc3745b5d14e9fd3072aa31d799d7877 on my Linux machine using Python 3.6, and running the unit test suite using:
```bash
python -m pytest python/tests/unit 
```
I get the following error:
```python-traceback                                     
Traceback (most recent call last):
  File "/home/jjerphan/.local/share/mambaforge/envs/arcticdb3.6/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/jjerphan/.local/share/mambaforge/envs/arcticdb3.6/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/jjerphan/.local/share/mambaforge/envs/arcticdb3.6/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/jjerphan/.local/share/mambaforge/envs/arcticdb3.6/lib/python3.6/site-packages/pytest/__init__.py", line 3, in <module>
    from . import collect
  File "/home/jjerphan/.local/share/mambaforge/envs/arcticdb3.6/lib/python3.6/site-packages/pytest/collect.py", line 8, in <module>
    from _pytest.deprecated import PYTEST_COLLECT_MODULE
  File "/home/jjerphan/.local/share/mambaforge/envs/arcticdb3.6/lib/python3.6/site-packages/_pytest/deprecated.py", line 13, in <module>
    from _pytest.warning_types import PytestDeprecationWarning
  File "/home/jjerphan/.local/share/mambaforge/envs/arcticdb3.6/lib/python3.6/site-packages/_pytest/warning_types.py", line 6, in <module>
    import attr
  File "/home/jjerphan/.local/share/mambaforge/envs/arcticdb3.6/lib/python3.6/site-packages/attr/__init__.py", line 10, in <module>
    from . import converters, exceptions, filters, setters, validators
  File "/home/jjerphan/.local/share/mambaforge/envs/arcticdb3.6/lib/python3.6/site-packages/attr/converters.py", line 10, in <module>
    from ._compat import _AnnotationExtractor
  File "/home/jjerphan/.local/share/mambaforge/envs/arcticdb3.6/lib/python3.6/site-packages/attr/_compat.py", line 12, in <module>
    from typing import _GenericAlias
ImportError: cannot import name '_GenericAlias'
```

[`typing._GenericAlias` has been introduced in Python 3.7](https://github.com/python/cpython/pull/4906).

Yet, it seems that some recent PR CI runs have not known this issue (for instance #328 had [3.6 Linux / unit](https://github.com/man-group/ArcticDB/actions/runs/4882197121/jobs/8712538328) ran successfully).

I am trying to understand what is going wrong here. Should part of the configuration be adapted?

**Comment by poodlewars** [comment]
Commenting on your local run, perhaps your `attrs` installation is too new? Installing from PyPi from 3.6 gives me 22.2.0 which doesn't have this issue. Could you confirm your version?

```
In [1]: import attr._compat

In [2]: import attr

In [3]: attr.__version__
Out[3]: '22.2.0'

In [4]: import sys

In [5]: sys.version
Out[5]: '3.6.8 (default, Nov 16 2020, 16:55:22) \n[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]'
```

**Comment by jjerphan** [comment]
Indeed, the version of the `attr`, `responses`, and `hypothesis` are too recent for Python 3.6.

Pinning previous versions that are supported for Python 3.6 when using conda/mamba should resolve the problem. In my case, the test suite works locally with:
 - `attr==22.2.0`
 - `responses==0.17.0`
 - `hypothesis==6.31.6` 

---

<details>
<summary>Full original environment specification</summary>

```
# packages in environment at /home/jjerphan/.local/share/mambaforge/envs/arcticdb3.6:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
asn1crypto                1.5.1              pyhd8ed1ab_0    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0             pyh71513ae_0    conda-forge
aws-c-auth                0.6.21               hd93a3ba_3    conda-forge
aws-c-cal                 0.5.20               hd3b2fe5_3    conda-forge
aws-c-common              0.8.5                h166bdaf_0    conda-forge
aws-c-compression         0.2.16               hf5f93bc_0    conda-forge
aws-c-event-stream        0.2.17               h57874a7_1    conda-forge
aws-c-http                0.7.0                h96ef541_0    conda-forge
aws-c-io                  0.13.12              h57ca295_1    conda-forge
aws-c-mqtt                0.7.13              h0b5698f_12    conda-forge
aws-c-s3                  0.2.1                h5d7e488_4    conda-forge
aws-c-sdkutils            0.1.7                hf5f93bc_0    conda-forge
aws-checksums             0.1.14               h6027aba_0    conda-forge
aws-crt-cpp               0.18.16              h26430d7_8    conda-forge
aws-sam-translator        1.55.0             pyhd8ed1ab_0    conda-forge
aws-sdk-cpp               1.11.2               h56135f1_0    conda-forge
aws-xray-sdk              2.12.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bitmagic                  7.13.4               ha770c72_0    conda-forge
boost-cpp                 1.78.0               h6582d0a_3    conda-forge
boto3                     1.21.21            pyhd8ed1ab_0    conda-forge
botocore                  1.24.21            pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py36h8f6f2f9_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2021.5.30        py36h5fab9bb_0    conda-forge
cffi                      1.14.6           py36hd8eec40_1    conda-forge
cfn-lint                  0.72.5             pyhd8ed1ab_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.0.1            py36h5fab9bb_0    conda-forge
cmake                     3.25.2               h077f3f9_0    conda-forge
contextlib2               21.6.0             pyhd8ed1ab_0    conda-forge
cryptography              35.0.0           py36hb60f036_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cyrus-sasl                2.1.27               h957375c_6    conda-forge
dataclasses               0.8                pyh787bdff_2    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
docker-py                 5.0.2            py36h5fab9bb_0    conda-forge
docker-pycreds            0.4.0                      py_0    conda-forge
double-conversion         3.2.0                h27087fc_1    conda-forge
doxygen                   1.9.6                hf41c82b_0    conda-forge
ecdsa                     0.18.0             pyhd8ed1ab_1    conda-forge
enum-compat               0.0.3                    pypi_0    pypi
execnet                   1.9.0              pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hcb278e6_1    conda-forge
flask                     2.0.3              pyhd8ed1ab_0    conda-forge
flask_cors                3.0.10             pyhd3deb0d_0    conda-forge
fmt                       9.1.0                h924138e_0    conda-forge
folly                     2022.10.31.00        h1234567_1    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
future                    0.18.2           py36h5fab9bb_3    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
glog                      0.6.0                h6f12383_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gmpy2                     2.1.0b5          py36h3f4d9dc_0    conda-forge
graphql-core              3.2.3              pyhd8ed1ab_0    conda-forge
grpcio                    1.48.2                   pypi_0    pypi
grpcio-tools              1.48.2                   pypi_0    pypi
gtest                     1.13.0               h00ab1b0_1    conda-forge
hypothesis                6.47.1             pyhd8ed1ab_0    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.8.1            py36h5fab9bb_0    conda-forge
importlib_metadata        4.8.1                hd8ed1ab_1    conda-forge
importlib_resources       3.3.1              pyhd8ed1ab_1    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
ipython                   7.16.1           py36he448a4c_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isodate                   0.6.1              pyhd8ed1ab_0    conda-forge
itsdangerous              2.0.1              pyhd8ed1ab_0    conda-forge
jedi                      0.17.2           py36h5fab9bb_1    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
jschema-to-python         1.2.3              pyhd8ed1ab_0    conda-forge
jsondiff                  2.0.0              pyhd8ed1ab_0    conda-forge
jsonpatch                 1.32               pyhd8ed1ab_0    conda-forge
jsonpickle                2.2.0              pyhd8ed1ab_0    conda-forge
jsonpointer               2.0                        py_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
junit-xml                 1.9                pyh9f0ad1d_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.3.1            py36h605e78d_1    conda-forge
krb5                      1.20.1               hf9c8cef_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libaio                    0.3.113              h166bdaf_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbson                   1.21.2               h27087fc_0    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcurl                   7.87.0               h6312ad2_0    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libmongoc                 1.21.1               h15e390e_0    conda-forge
libmongocxx               3.6.7                h6e2fe03_0    conda-forge
libnghttp2                1.51.0               hdcd2b5c_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libntlm                   1.4               h7f98852_1002    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libprotobuf               3.21.12              h3eb15da_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsqlite                 3.40.0               h753d276_1    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtiff                   4.3.0                h0fcbabc_4    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libuv                     1.44.2               h166bdaf_0    conda-forge
libwebp-base              1.3.0                h0b41bf4_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
lmdb                      0.9.29               h166bdaf_1    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
markupsafe                2.0.1            py36h8f6f2f9_0    conda-forge
matplotlib-base           3.3.4            py36hd391965_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mock                      5.0.2              pyhd8ed1ab_0    conda-forge
more-itertools            9.1.0              pyhd8ed1ab_0    conda-forge
moto                      4.1.8              pyhd8ed1ab_0    conda-forge
mpc                       1.3.1                hfe3b2da_0    conda-forge
mpfr                      4.2.0                hb012696_0    conda-forge
msgpack                   1.0.5                    pypi_0    pypi
msgpack-c                 6.0.0                hfc55251_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
networkx                  2.7                pyhd8ed1ab_0    conda-forge
numpy                     1.19.5           py36hfc0c790_2    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openapi-schema-validator  0.1.6              pyhd8ed1ab_0    conda-forge
openapi-spec-validator    0.3.3              pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.0                h7d73246_0    conda-forge
openssl                   1.1.1t               h0b41bf4_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.1.5            py36h284efc9_0    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
path                      16.2.0           py36h5fab9bb_0    conda-forge
path.py                   12.5.0                        0    conda-forge
pbr                       5.11.1             pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.3.2            py36h676a545_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0            py36h5fab9bb_1    conda-forge
prometheus-client         0.16.0                   pypi_0    pypi
prometheus-cpp            1.1.0                h751d214_1    conda-forge
prompt-toolkit            3.0.36             pyha770c72_0    conda-forge
prompt_toolkit            3.0.36               hd8ed1ab_0    conda-forge
protobuf                  3.19.6                   pypi_0    pypi
psutil                    5.8.0            py36h8f6f2f9_1    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pybind11                  2.8.0            py36h605e78d_0    conda-forge
pybind11-global           2.8.0            py36h605e78d_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.14.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_1    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyrsistent                0.16.0           py36h8c4c3a4_0    conda-forge
pysocks                   1.7.1            py36h5fab9bb_3    conda-forge
pytest                    6.2.5            py36h5fab9bb_0    conda-forge
pytest-fixture-config     1.7.0                      py_0    conda-forge
pytest-server-fixtures    1.7.0              pyhd8ed1ab_0    conda-forge
pytest-shutil             1.7.0              pyhd8ed1ab_1    conda-forge
pytest-sugar              0.9.7              pyhd8ed1ab_0    conda-forge
python                    3.6.15          hb7a2778_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-jose               3.3.0              pyh6c4a22f_1    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py36h8f6f2f9_1    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.28.1             pyhd8ed1ab_0    conda-forge
responses                 0.19.0             pyhd8ed1ab_0    conda-forge
retry                     0.9.2                      py_0    conda-forge
rhash                     1.4.3                h166bdaf_0    conda-forge
rsa                       4.9                pyhd8ed1ab_0    conda-forge
s2n                       1.3.31               hae46d1a_0    conda-forge
s3transfer                0.5.2              pyhd8ed1ab_0    conda-forge
sarif-om                  1.0.4              pyhd8ed1ab_0    conda-forge
scipy                     1.5.3            py36h81d768a_1    conda-forge
setuptools                58.0.4           py36h5fab9bb_2    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
spdlog                    1.11.0               h9b3ece8_1    conda-forge
sqlite                    3.40.0               h4ff8645_1    conda-forge
sshpubkeys                3.3.1              pyhd8ed1ab_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
termcolor                 1.1.0              pyhd8ed1ab_3    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py36h8f6f2f9_1    conda-forge
traitlets                 4.3.3              pyhd8ed1ab_2    conda-forge
typing_extensions         4.1.1              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
websocket-client          1.3.1              pyhd8ed1ab_0    conda-forge
werkzeug                  2.0.2              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
wrapt                     1.13.1           py36h8f6f2f9_0    conda-forge
xmltodict                 0.13.0             pyhd8ed1ab_0    conda-forge
xxhash                    3.2.0                    pypi_0    pypi
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge
```
</details>
