### ISSUE TITLE
 Failed to find segment for key 'C:my_lib' : No response body.

### ISSUE THREAD

**Issue by markeasec** [man-group/ArcticDB#461]
### Describe the bug

Continuation of #410 .

I get errors when trying to access or initialize a library.

```
[2023-06-02 13:20:32.666] [arcticdb] [warning] Failed to find segment for key 'C:my_lib' : No response body.
Traceback (most recent call last):
File "migrate_arctic.py", line 20, in
lib = as3['my_lib']
File "/home/ec2-user/.local/lib/python3.7/site-packages/arcticdb/arctic.py", line 96, in getitem
self._library_manager.get_library(name),
arcticdb_ext.exceptions.StorageException: Composite: C:my_lib,
```

Im guessing this is due to the library not being initialized, but when I try to initialize I get this error:

```
[2023-06-02 13:24:17.098] [arcticdb] [warning] Failed to iterate key type with key 'C' AccessDenied: Access Denied
[2023-06-02 13:24:17.121] [arcticdb] [error] E_ASSERTION_FAILURE Failed to write s3 with key 'C:my_lib' AccessDenied: Access Denied
Traceback (most recent call last):
File "migrate_arctic.py", line 10, in
as3.create_library('my_lib')
File "/home/ec2-user/.local/lib/python3.7/site-packages/arcticdb/arctic.py", line 159, in create_library
self._library_manager.write_library_config(library_config, name)
arcticdb_ext.exceptions.InternalException: E_ASSERTION_FAILURE Failed to write s3 with key 'C:my_lib' AccessDenied: Access Denied
```
Im trying to initialize like so:

```python
as3.create_library('my_lib')
```

### Steps/Code to Reproduce

```python
from arcticdb import Arctic as s3arc
as3 = s3arc('s3://s3.us-east-1.amazonaws.com:chum_bucket?aws_auth=true')
lib = as3['my_lib']
```

### Expected Results

should be able to connect to or initialize a library

### OS, Python Version and ArcticDB Version

OS (Including Linux Distribution)
Amazon Linux AMI 2

Python Version
3.7

ArcticDB Version
1.0.1

### Backend storage used

AWS S3

**Comment by mehertz** [comment]
How do you authenticate? 

Can you please turn on debug logging https://docs.arcticdb.io/runtime_config/

In short:

`ARCTICDB_all_loglevel=DEBUG` `ARCTICDB_AWS_LogLevel_int=6` (env vars)

You'll get more logging on the terminal and a file in your current working directory that details the AWS S3 logs. 

There will likely be a lot of data - if you could post any obvious errors that would be a great starting point. 

Agree that our URI is custom and confusing. We should resolve this.

**Comment by mehertz** [comment]
I'm going to close. Happy to re-open once you have more logging output or if you know what the AWS auth mechanism is.
