### ISSUE TITLE
Storage Exception - Composite X:Y

### ISSUE THREAD

**Issue by balajipitchumani** [man-group/ArcticDB#609]
### Describe the bug

Hi Team
I am trying to read 100mil CSV into a symbol. Ingestion seems to have gone fine as below however when I try to read, I am getting storage exception as below.

### Steps/Code to Reproduce

Ingestion
```python
import pandas as pd
import arcticdb
from arcticdb import Arctic
from arcticdb.config import set_log_level
import faulthandler

faulthandler.enable()

print('pandas', pd.__version__)
print('arcticdb', arcticdb.__version__)

set_log_level('DEBUG')

arctic = Arctic('lmdb://c:/py/db.lmdb')
if 'bhu' not in arctic.list_libraries():
    arctic.create_library('bhu')
library = arctic['bhu']

tab='c00'
library.delete(tab)
chunksize = 1000000
cols = ['s','d','o','h','l','c','a','v']
with pd.read_csv('c:/users/bala/py/' + tab + '.csv', chunksize=chunksize, index_col='d', parse_dates=['d'], header=None, names=cols, dtype={'s':'str', 'o': 'float64', 'h': 'float64', 'l': 'float64', 'c': 'float64', 'a': 'float64', 'v': 'float64'}) as reader:
    for chunk in reader:
        print(chunk.info())
        library.append(tab, chunk,validate_index=False)
```

read
```python
import pandas as pd
import arcticdb
from arcticdb import Arctic
from arcticdb.config import set_log_level
import faulthandler

faulthandler.enable()

print('pandas', pd.__version__)
print('arcticdb', arcticdb.__version__)

set_log_level('DEBUG')

arctic = Arctic('lmdb://c:/py/db.lmdb')
if 'bhu' not in arctic.list_libraries():
    arctic.create_library('bhu')
library = arctic['bhu']

q = QueryBuilder()
q = q[(q['s'] == 'ACC')]
#q = q.groupby('s').agg({'d':'max'})
df = library.read('c00',query_builder=q).data
df.head(1)
```

### Expected Results

```
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1000000 entries, 2011-01-03 to 2013-10-01
Data columns (total 7 columns):
 #   Column  Non-Null Count    Dtype  
---  ------  --------------    -----  
 0   s       1000000 non-null  object 
 1   o       1000000 non-null  float64
 2   h       1000000 non-null  float64
 3   l       1000000 non-null  float64
 4   c       1000000 non-null  float64
 5   a       1000000 non-null  float64
 6   v       1000000 non-null  float64
dtypes: float64(6), object(1)
memory usage: 61.0+ MB
None
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1000000 entries, 2013-10-01 to 2016-07-04
Data columns (total 7 columns):
 #   Column  Non-Null Count    Dtype  
---  ------  --------------    -----  
 0   s       1000000 non-null  object 
 1   o       1000000 non-null  float64
 2   h       1000000 non-null  float64
 3   l       1000000 non-null  float64
 4   c       1000000 non-null  float64
 5   a       1000000 non-null  float64
 6   v       1000000 non-null  float64
dtypes: float64(6), object(1)
memory usage: 61.0+ MB
None
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1000000 entries, 2016-07-04 to 2019-01-18
Data columns (total 7 columns):
 #   Column  Non-Null Count    Dtype  
---  ------  --------------    -----  
 0   s       1000000 non-null  object 
 1   o       1000000 non-null  float64
 2   h       1000000 non-null  float64
 3   l       1000000 non-null  float64
 4   c       1000000 non-null  float64
 5   a       1000000 non-null  float64
 6   v       1000000 non-null  float64
dtypes: float64(6), object(1)
memory usage: 61.0+ MB
None
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1000000 entries, 2019-01-18 to 2021-06-29
Data columns (total 7 columns):
 #   Column  Non-Null Count    Dtype  
---  ------  --------------    -----  
 0   s       1000000 non-null  object 
 1   o       1000000 non-null  float64
 2   h       1000000 non-null  float64
 3   l       1000000 non-null  float64
 4   c       1000000 non-null  float64
 5   a       1000000 non-null  float64
 6   v       1000000 non-null  float64
dtypes: float64(6), object(1)
memory usage: 61.0+ MB
None
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 959748 entries, 2021-06-29 to 2023-07-11
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   s       959748 non-null  object 
 1   o       959748 non-null  float64
 2   h       959748 non-null  float64
 3   l       959748 non-null  float64
 4   c       959748 non-null  float64
 5   a       959748 non-null  float64
 6   v       959748 non-null  float64
dtypes: float64(6), object(1)
memory usage: 58.6+ MB
None
```

read exception stack

```
pandas 2.0.3
arcticdb 1.5.0
---------------------------------------------------------------------------
StorageException                          Traceback (most recent call last)
Cell In[11], line 22
     20 q = q[(q['s'] == 'ACC')]
     21 #q = q.groupby('s').agg({'d':'max'})
---> 22 df = library.read('c00',query_builder=q).data
     23 df.head(1)

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\arcticdb\version_store\library.py:858, in Library.read(self, symbol, as_of, date_range, columns, query_builder)
    796 def read(
    797     self,
    798     symbol: str,
   (...)
    802     query_builder: Optional[QueryBuilder] = None,
    803 ) -> VersionedItem:
    804     """
    805     Read data for the named symbol.  Returns a VersionedItem object with a data and metadata element (as passed into
    806     write).
   (...)
    856     2       7
    857     """
--> 858     return self._nvs.read(
    859         symbol=symbol, as_of=as_of, date_range=date_range, columns=columns, query_builder=query_builder
    860     )

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\arcticdb\version_store\_store.py:1525, in NativeVersionStore.read(self, symbol, as_of, date_range, row_range, columns, query_builder, **kwargs)
   1521     row_range = _SignedRowRange(row_range[0], row_range[1])
   1522 version_query, read_options, read_query = self._get_queries(
   1523     as_of, date_range, row_range, columns, query_builder, **kwargs
   1524 )
-> 1525 read_result = self._read_dataframe(symbol, version_query, read_query, read_options)
   1526 return self._post_process_dataframe(read_result, read_query)

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\arcticdb\version_store\_store.py:1590, in NativeVersionStore._read_dataframe(self, symbol, version_query, read_query, read_options)
   1589 def _read_dataframe(self, symbol, version_query, read_query, read_options):
-> 1590     return ReadResult(*self.version_store.read_dataframe_version(symbol, version_query, read_query, read_options))

StorageException: Composite: d:c00:4:0x39ef8d0652c32707@1689428954223617400[1624924800000000000,1632182400000000001], 
```

### OS, Python Version and ArcticDB Version

pandas 2.0.3

Python: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
OS: Windows-10-10.0.19045-SP0
ArcticDB: 1.5.0

### Backend storage used

LMDB

**Comment by jamesmunro** [comment]
Thanks for your bug report.  We will take a look.

**Comment by jamesmunro** [comment]
I've managed to replicate with self contained script, below.   Thanks for reporting this.  

Test:
```python
import numpy as np
import pandas as pd
import arcticdb
from arcticdb import Arctic, QueryBuilder
from arcticdb.config import set_log_level
import faulthandler

faulthandler.enable()

print('pandas', pd.__version__)
print('arcticdb', arcticdb.__version__)

set_log_level('DEBUG')

arctic = Arctic('lmdb://test.lmdb')
if 'test' not in arctic.list_libraries():
    arctic.create_library('test')
library = arctic['test']

library.delete('data')

n=10_000_000
df = pd.DataFrame(np.linspace(1, n*8, n*8).reshape(n, 8),
                  columns=['s','d','o','h','l','c','a','v'],
                  index=pd.date_range('1/1/2020', periods=n, freq="T"))

library.write('data', df)

q = QueryBuilder()
q = q[(q['o'] > 1_000_000.0)]

print('************* READ ****************')
library.read('data',query_builder=q)
```

Which generates the follow output
```
pandas 1.5.3
arcticdb 1.5.0
20230718 21:58:24.710735 30364 D arcticdb.version | Created versioned engine at 2500585304768 for library path _arctic_cfg  with config ~()
20230718 21:58:24.714139 30364 D arcticdb.version | Created versioned engine at 2500585309456 for library path test  with config ~(write_options {
  column_group_size: 127
  segment_row_size: 100000
  dynamic_strings: true
  recursive_normalizers: true
  use_tombstones: true
  fast_tombstone_all: true
}
symbol_list: true
)
20230718 21:58:24.714299 30364 D arcticdb.version | Command: delete_all_versions
20230718 21:58:24.715693 30364 D arcticdb.version | Command: delete_tree
20230718 21:58:24.715785 30364 D arcticdb.schedule | Task scheduler created with 16 24
20230718 21:58:24.719111 30364 D arcticdb.version | Candidate: 100 total of data keys
20230718 21:58:24.719165 30364 D arcticdb.version | Forbidden: 0 total of data keys
20230718 21:58:24.720886 30364 D arcticdb.version | Index keys deleted. Proceeding with 100 number of data keys
20230718 21:58:24.722474 30364 D arcticdb.version | Symbol List: remove_symbol: data
20230718 21:58:24.913947 30364 D arcticdb.version | Writing with pickle_on_failure=False, prune_previous_version=False, recursive_normalizers=True
20230718 21:58:24.914275 30364 D arcticdb.version | Normalizer used: <bound method DataFrameNormalizer.normalize of <arcticdb.version_store._normalization.DataFrameNormalizer object at 0x0000024636042E00>>
20230718 21:58:24.914410 30364 D arcticdb.version | Index has no name, defaulting to 'index'
20230718 21:58:24.929653 30364 D arcticdb.version | Command: write_versioned_dataframe
20230718 21:58:25.452386 30364 D arcticdb.version | Symbol List: add_symbol: data
************* READ ****************
20230718 21:58:25.454026 30364 D arcticdb.version | Command: read_dataframe
20230718 21:58:25.470653 932 D arcticdb.version | Filter returned empty result
Traceback (most recent call last):
  File "C:\Users\james\Workspace\arcticdb-scratch\composite_issue.py", line 33, in <module>
    library.read('data',query_builder=q)
  File "C:\Users\james\AppData\Roaming\Python\Python310\site-packages\arcticdb\version_store\library.py", line 858, in read
    return self._nvs.read(
  File "C:\Users\james\AppData\Roaming\Python\Python310\site-packages\arcticdb\version_store\_store.py", line 1525, in read
    read_result = self._read_dataframe(symbol, version_query, read_query, read_options)
  File "C:\Users\james\AppData\Roaming\Python\Python310\site-packages\arcticdb\version_store\_store.py", line 1590, in _read_dataframe
    return ReadResult(*self.version_store.read_dataframe_version(symbol, version_query, read_query, read_options))
arcticdb_ext.exceptions.StorageException: Composite: d:data:101:0x8d51fc394258f829@1689713905240873400[1679836800000000000,1685836740000000001],
```

We've been having problems with the LMDB backend on Windows.  It's possible that issue #229 will fix this.

**Comment by balajipitchumani** [comment]
Thanks for getting back. I tried now in Ubuntu Linux, ingestion went fine, I can now see a 2GB data file within my arcticdb folder as below. However, trying to read gives a different storage exception.

![image](https://github.com/man-group/ArcticDB/assets/22409549/c6116eb1-36a9-49b0-b7c4-4d21d6b5e776)

**Comment by balajipitchumani** [comment]
I tried in Linux and can confirm now that the issue is resolved. Many thanks for your timely support.
