### ISSUE TITLE
Fetching library again causes next write to fail with lmdb

### ISSUE THREAD

**Issue by jamesmunro** [man-group/ArcticDB#889]
### Describe the bug

Fetching library from Arctic instance a second time causes next write to that library to fail.

### Steps/Code to Reproduce

```python
import numpy as np
from arcticdb import Arctic
a = Arctic("lmdb://test.lmdb")
lib = a.get_library('l0', create_if_missing=True)
lib.write('symbol', np.arange(10))
lib = a.get_library('l0')
lib.write('symbol', np.arange(10))
```

Output:
```
[2023-09-21 21:27:45.219] [arcticdb] [warning] Loading versions from storage via ref key failed with error: mdb_txn_begin: Invalid argument for stream symbol. Retrying
Traceback (most recent call last):
  File "/home/james/workspace/arcticdb-cli/weirdbug.py", line 9, in <module>
    lib.write('symbol', pd.DataFrame({'a': [1,2,3]}))
  File "/home/james/miniforge3/envs/cli/lib/python3.11/site-packages/arcticdb/version_store/library.py", line 421, in write
    return self._nvs.write(
           ^^^^^^^^^^^^^^^^
  File "/home/james/miniforge3/envs/cli/lib/python3.11/site-packages/arcticdb/version_store/_store.py", line 571, in write
    vit = self.version_store.write_versioned_dataframe(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
arcticdb_ext.exceptions.InternalException: lmdb::runtime_error(mdb_txn_begin: Invalid argument)
```

### Expected Results

No error

### OS, Python Version and ArcticDB Version

Python: 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0]
OS: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
ArcticDB: 3.0.0

### Backend storage used

LMDB

**Comment by poodlewars** [comment]
We should be caching the library instance, due to this LMDB limitation:

```
Threads and Processes

LMDB uses POSIX locks on files, and these locks have issues if one process opens a file multiple times. Because of this, do not [mdb_env_open()](http://www.lmdb.tech/doc/group__mdb.html#ga32a193c6bf4d7d5c5d579e71f22e9340) a file multiple times from a single process. Instead, share the LMDB environment that has opened the file across all threads. Otherwise, if a single process opens the same environment multiple times, closing it once will remove all the locks held on it, and the other instances will be vulnerable to corruption from other processes.

Also note that a transaction is tied to one thread by default using Thread Local Storage. If you want to pass read-only transactions across threads, you can use the [MDB_NOTLS](http://www.lmdb.tech/doc/group__mdb__env.html#ga5dca84a576d14b4bfe2deddc2dc622d3) option on the environment.
```

I thought I'd implemented this, but I clearly haven't done it or tested it correctly. I'll have a look.

**Comment by joe-iddon** [comment]
For what it's worth I couldn't reproduce:

```
>>> import numpy as np
>>> from arcticdb import Arctic
>>> a = Arctic("lmdb://test.lmdb")
>>> lib = a.get_library('l0', create_if_missing=True)
>>> lib.write('symbol', np.arange(10))
VersionedItem(symbol='symbol', library='l0', data=n/a, version=0, metadata=None, host='LMDB(path=/users/is/jiddon/test.lmdb)')
>>> lib = a.get_library('l0')
>>> lib.write('symbol', np.arange(10))
VersionedItem(symbol='symbol', library='l0', data=n/a, version=1, metadata=None, host='LMDB(path=/users/is/jiddon/test.lmdb)')
```

On:

```
Python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
OS: Linux-5.15.0-76-generic-x86_64-with-glibc2.35
ArcticDB: 3.0.0
```

**Comment by poodlewars** [comment]
I can't repro either, but there does seem to be a bug in `Arctic#__getitem__` since the `self._open_libraries` field is not updated.

**Comment by jamesmunro** [comment]
I couldn't reproduce on another machine.

```
Python: 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0]
OS: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
ArcticDB: 3.0.0
```

**Comment by jamesmunro** [comment]
However I did get a similar error with `has_symbol` after multiple `get_library` calls.

```
Traceback (most recent call last):
  File "/home/james/workspace/arcticdb-cli/exhausted.py", line 38, in <module>
    exercise_library(arctic)
  File "/home/james/workspace/arcticdb-cli/exhausted.py", line 30, in exercise_library
    library = arctic.get_library('FUTURES')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/miniforge3/envs/cli/lib/python3.11/site-packages/arcticdb/arctic.py", line 231, in get_library
    lib = self[name]
          ~~~~^^^^^^
  File "/home/james/miniforge3/envs/cli/lib/python3.11/site-packages/arcticdb/arctic.py", line 177, in __getitem__
    if not self._library_manager.has_library(name):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
arcticdb_ext.exceptions.InternalException: lmdb::runtime_error(mdb_txn_begin: Invalid argument)
```
which I'm now struggling to reproduce
